spring:
  server:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
